"""
A local dashboard preview — an alternative to Power BI when you don't have
the Power BI Desktop app handy. Reads data from a CSV (generated by
generate_sample_data.py or fetched from the GetSalesSummary endpoint) and
renders an interactive HTML chart.

Usage:
    python generate_sample_data.py
    python dashboard.py
"""
import pandas as pd
import plotly.express as px

df = pd.read_csv("sample_sales.csv", parse_dates=["sale_date"])

by_store = df.groupby("store_name", as_index=False)["value"].sum().sort_values("value", ascending=False)
fig1 = px.bar(by_store, x="store_name", y="value", title="Sales value by store (30 days)")

daily = df.groupby("sale_date", as_index=False)["value"].sum()
fig2 = px.line(daily, x="sale_date", y="value", title="Daily sales value (all stores)")

by_product = df.groupby("product_name", as_index=False)["units_sold"].sum()
fig3 = px.pie(by_product, names="product_name", values="units_sold", title="Share of units sold by product")

with open("dashboard_preview.html", "w", encoding="utf-8") as f:
    f.write("<html><head><meta charset='utf-8'><title>Store Insights — preview</title></head><body>")
    f.write("<h1>Store Insights — local data preview</h1>")
    f.write(fig1.to_html(full_html=False, include_plotlyjs="cdn"))
    f.write(fig2.to_html(full_html=False, include_plotlyjs=False))
    f.write(fig3.to_html(full_html=False, include_plotlyjs=False))
    f.write("</body></html>")

print("Saved dashboard_preview.html — open it in a browser.")
